id: I972428C4
default_language: en-us
source: ''
initial_creation_type: tmx
imported: 2022-12-14 18:01:27.893326+00:00
last_modified: 2022-12-14 18:01:27.893331+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-071-012
  eft-text-version: 1.1.3 2020
  title: Toh_298-The_Gandi_Sutra-v2
bases:
  F991:
    source_metadata: null
    order: 1
    base_file: F991.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
